#!/usr/bin/env bash

# Install dependencies
if [ "$1" = "arch" ]; then
    pacman -Syu --noconfirm base-devel \
                            cmake \
                            clang \
                            libc++ \
                            git \
                            python \
                            openssl \
                            perl
elif [ "$1" = "fedora" ]; then
    dnf groupinstall -y "C Development Tools and Libraries"
    dnf install -y cmake \
                    clang \
                    git \
                    libcxx \
                    libcxx-static \
                    libcxxabi-static \
                    openssl-devel \
                    perl
else
    apt update
    # https://stackoverflow.com/a/44333806
    if ! dpkg -l tzdata > /dev/null; then
    ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
    DEBIAN_FRONTEND=noninteractive apt install -y tzdata
    dpkg-reconfigure --frontend noninteractive tzdata
    fi
    apt install -y --no-install-recommends ca-certificates \
                                                  build-essential \
                                                  cmake \
                                                  clang \
                                                  libc++-dev \
                                                  libc++abi-dev \
                                                  git \
                                                  python3 \
                                                  libtool \
                                                  automake \
                                                  autoconf \
                                                  pkgconf \
                                                  openssl \
                                                  libssl-dev
        fi

# Build libcrypto.a (3.3)
if [ -z "$(find /usr -name libcrypto.a)" ]; then
    # allow static libs on Arch
    sed -i 's/!staticlibs/staticlibs/g' /etc/makepkg.conf &> /dev/null || true
    # fix perl's bin not being in $PATH on Arch
    source /etc/profile &> /dev/null || true
    git clone --depth=1 https://github.com/openssl/openssl -b openssl-3.3
    cd openssl
    ./config
    make -j build_libs
    mkdir -p /usr/local/lib
    cp libcrypto.a /usr/local/lib
    cd ../
else
    echo "libcrypto.a exists. Skipping..."
fi

# Submodules
if [ -n "$CI" ] && [ -d "$PWD/.git" ];  then
    git config --global --add safe.directory $PWD
    git submodule update --init --recursive
fi
