#!/usr/bin/env bash

set -e
shopt -s extglob

info() { echo "[info] $1"; }

ROOT="${PWD}"
STAGING="${ROOT}/staging"
PACKAGES="${ROOT}/packages"
export INSTALLPREFIX="${STAGING}/prefix/linux/iphone"
if [[ -x $(command -v nproc) ]]; then
	export JOBS=$(nproc --all)
elif [[ -x $(command -v sysctl) ]]; then
	export JOBS=$(sysctl -n hw.ncpu)
else
	export JOBS=1
fi

info "Creating prefix dir"
rm -rf "${STAGING}"
mkdir -p "${INSTALLPREFIX}"

info "Building LLVM tools"
cd "${ROOT}/apple-libtapi/"
cmake -S src/llvm/ -B build \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="${INSTALLPREFIX}" \
	-DCMAKE_CXX_FLAGS="-I${PWD}/../src/llvm/projects/clang/include -I${PWD}/projects/clang/include" \
	-DLLVM_INCLUDE_TESTS=OFF
cmake --build build --target clangBasic -- -j "${JOBS}"
cmake --build build --target libtapi dsymutil install-libtapi install-tapi-headers install-tapi install-dsymutil -- -j "${JOBS}"

info "Building cctools"
cd "${ROOT}/apple-libdispatch"
cmake -B build \
	-DCMAKE_BUILD_TYPE=RELEASE \
	-DCMAKE_INSTALL_PREFIX="${INSTALLPREFIX}"
cmake --build build --target install -- -j "${JOBS}"

cd "${ROOT}/cctools-port/cctools"
./configure \
	--prefix="${INSTALLPREFIX}" \
	--with-libtapi="${INSTALLPREFIX}" \
	--with-libdispatch="${INSTALLPREFIX}" \
	--with-libblocksruntime="${INSTALLPREFIX}" \
	--target="aarch64-apple-darwin14" \
	--program-prefix="" \
	LDFLAGS="-Wl,-rpath,'\$\$ORIGIN/../lib' -Wl,-z,origin"
make PROGRAM_PREFIX="" CXXABI_LIB="-l:libc++abi.a" install -j "${JOBS}"

info "Building libplist"
cd "${ROOT}/libplist"
PLIST_PREFIX="${STAGING}/libplist-install"
mkdir -p "${PLIST_PREFIX}"
LC_ALL=C ./autogen.sh --prefix="${PLIST_PREFIX}" --without-cython PACKAGE_VERSION=latest
make install -j "${JOBS}"

info "Building ldid"
cd "${ROOT}/ldid"
make DESTDIR="${INSTALLPREFIX}" PREFIX="" \
	LIBCRYPTO_LIBS="-l:libcrypto.a -lpthread -ldl" \
	LIBPLIST_LIBS="${PLIST_PREFIX}/lib/libplist-2.0.a" LIBPLIST_INCLUDES="-I${PLIST_PREFIX}/include" \
	install \
	-j "${JOBS}"

info "Packaging toolchain"
mkdir -p "${PACKAGES}"
cd "${STAGING}/prefix"
tar -czf "${PACKAGES}/darwin-tools.tar.gz" linux

info "Done!"
