name: Create Release

on:
  - push
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: docker://ubuntu:20.04
            name: ubuntu-20.04
          - runner: docker://ubuntu:22.04
            name: ubuntu-22.04
          - runner: docker://archlinux:latest
            name: arch
          - runner: docker://fedora:latest
            name: fedora

    runs-on: ubuntu-latest
    container: ${{ matrix.runner }}
    steps:
    - name: Install dependencies
      run: |
        if [ "${{ matrix.name }}" = "arch" ]; then
          pacman -Syu --noconfirm base-devel \
                                  cmake \
                                  clang \
                                  libc++ \
                                  git \
                                  python \
                                  openssl \
                                  perl
        elif [ "${{ matrix.name }}" = "fedora" ]; then
          dnf groupinstall -y "C Development Tools and Libraries"
          dnf install -y cmake \
                          clang \
                          git \
                          libcxx \
                          libcxx-static \
                          libcxxabi-static \
                          openssl-devel \
                          perl
        else
          apt update
          # https://stackoverflow.com/a/44333806
          if ! dpkg -l tzdata > /dev/null; then
            ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
            DEBIAN_FRONTEND=noninteractive apt install -y tzdata
            dpkg-reconfigure --frontend noninteractive tzdata
          fi
          apt install -y --no-install-recommends ca-certificates \
                                                  build-essential \
                                                  cmake \
                                                  clang \
                                                  libc++-dev \
                                                  libc++abi-dev \
                                                  git \
                                                  python3 \
                                                  libtool \
                                                  automake \
                                                  autoconf \
                                                  pkgconf \
                                                  openssl \
                                                  libssl-dev
        fi

    - name: Build libcrypto.a (3.3)
      run: |
        if [ -z "$(find /usr -name libcrypto.a)" ]; then
          # allow static libs on Arch
          sed -i 's/!staticlibs/staticlibs/g' /etc/makepkg.conf &> /dev/null || true
          # fix perl's bin not being in $PATH on Arch
          source /etc/profile &> /dev/null || true
          git clone --depth=1 https://github.com/openssl/openssl -b openssl-3.3
          cd openssl
          ./config
          make -j build_libs
          mkdir -p /usr/local/lib
          cp libcrypto.a /usr/local/lib
        else
          echo "libcrypto.a exists. Skipping..."
        fi

    - uses: actions/checkout@v4
    - name: Submodules
      run: |
        git config --global --add safe.directory $PWD
        git submodule update --init --recursive

    - name: Build Release
      run: |
        CC=clang CXX=clang++ ./prepare-toolchain
        mv packages/darwin-tools.tar.gz packages/darwin-tools-${{ matrix.name }}.tar.gz

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DT-${{ matrix.name }}
        path: packages/darwin-tools-${{ matrix.name }}.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          pattern: DT-*
          path: packages

      - name: Create release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release create "$TAG" --draft --title "Draft Release"

      - name: Attach builds to release
        run: |
          TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
          gh release upload "$TAG" packages/**/*.tar.gz
