name: Create Release

on:
  - push
  - workflow_dispatch

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  create_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Create Release
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release create "$TAG" --draft --title "Draft Release"

  build:
    needs: create_release
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: docker://ubuntu:20.04
            name: ubuntu-20.04
          - runner: docker://ubuntu:22.04
            name: ubuntu-22.04
          - runner: docker://archlinux:latest
            name: arch
          - runner: docker://fedora:latest
            name: fedora

    runs-on: ubuntu-latest
    container: ${{ matrix.runner }}
    steps:
    - name: Install dependencies
      run: |
        if [ "${{ matrix.name }}" = "arch" ]; then
          pacman -Syu --noconfirm base-devel cmake clang libc++ git python
        elif [ "${{ matrix.name }}" = "fedora" ]; then
          dnf groupinstall -y "Development Tools" "Development Libraries"
          dnf install -y cmake clang libcxx
        else
          apt update
          # https://stackoverflow.com/a/44333806
          if ! dpkg -l tzdata > /dev/null; then
            ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime
            DEBIAN_FRONTEND=noninteractive apt install -y tzdata
            dpkg-reconfigure --frontend noninteractive tzdata
          fi
          apt install -y --no-install-recommends ca-certificates build-essential cmake clang libc++-dev libc++abi-dev git python3
        fi

    - uses: actions/checkout@v4
    - name: Submodules
      run: |
        git config --global --add safe.directory $PWD
        git submodule update --init --recursive

    - name: Build Release
      id: build_release
      run: |
        CC=clang CXX=clang++ ./prepare-toolchain --
        mv packages/darwin-tools.tar.gz /github/workspace/packages/darwin-tools-${{ matrix.name }}.tar.gz

    - name: Attach Build To Release
      run: |
        TAG="${GITHUB_REF##*/}-${GITHUB_SHA:0:7}"
        gh release upload "$TAG" packages/*.tar.gz
